Add an option to retry on every error
membraneframework/membrane-element-httpoison pull request #9
Opened 2019-01-16 15:02 UTC by bblaszkow06

2019-01-25 18:05 UTC, mat-hek requested changes
Can you also justify why in some places you introduce a delay before reconnecting while in others you don't, and how do you guarantee delay happens after _another_ retry? Also, I think retries counter should be reset after some time.

2019-01-29 17:15 UTC, bblaszkow06 commented on lib/membrane_element_httpoison/source.ex
> +  defp retry(_reason, %{retry_delay: delay} = state, true) do
?

2019-02-25 15:31 UTC, bblaszkow06 commented on lib/membrane_element_httpoison/source.ex
> +        warn("HTTPoison.stream_next/1 error: #{inspect(reason)}")
meh, `warn_error` is a bit too verbose, stacktrace is not needed

2019-02-25 16:05 UTC, mat-hek approved these changes

2019-02-25 16:55 UTC, merged